### ISSUE TITLE
Why does the TimestampsMixin not enable timezones?

### ISSUE THREAD

**Issue by jonbiemond** [absent1706/sqlalchemy-mixins#112]
I'm curious as to why the TimestampsMixin explicitly disable timezones in the TIMESTAMP fields.
https://github.com/absent1706/sqlalchemy-mixins/blob/d1475a58d9f5b27dd7a794d7c3acb496aad6fd29/sqlalchemy_mixins/timestamp.py#L14

Looking at the relevant [commit message](https://github.com/absent1706/sqlalchemy-mixins/commit/6b1defaf3f76d437aa7df70e38d5ab935c352a49) it seems like @metheoryt meant to enable them.

Is there any reason to have timezones disabled on those fields?

**Comment by metheoryt** [comment]
Hi @jonbiemond ! 
As I remember, it didn’t seem useful to me to have a timezone at those columns at that moment. 
Since the columns aren’t meant to be updated by end users, there is no point to store a timezone here.
If you need to display that data in a timezone-aware approach, it is better to convert it to desired timezone at displaying time. 

However, it is a general rule and might not apply for your case. If you need timezone aware timestamps for those fields, I could suggest you to add them manually.

**Comment by jonbiemond** [comment]
Hello!

Yes, that makes perfect sense. Thank you! I appreciate the suggestion.
