### ISSUE TITLE
Missing attributes in SerializeMixin

### ISSUE THREAD

**Issue by omrihar** [absent1706/sqlalchemy-mixins#21]
It seems that the `SerializeMixin` is only serializing the columns and relationships in its `to_dict` method. This misses attributes defined on the model such as Hybrid Attributes.
A reference implementation that handles it can be found here: https://wakatime.com/blog/32-flask-part-1-sqlalchemy-models-to-json

Unfortunately in order to not miss anything, one has to use `dir()` and remove all the properties that are already accounted for in the Columns and Relationships, as well as dropping everything starting with an underscore.

Other than that, I really like your Mixin library and plan to use it in my upcoming project :) 
Thanks!

**Comment by omrihar** [comment]
OK, so I just noticed the InspectMixin that handles these properties, but still the `SerializeMixin` does not show other attributes. Is this on purpose or perhaps it can be a nice addition to request for these properties as well?

**Comment by absent1706** [comment]
Hi @omrihar !
Yes, that's true: `SerializeMixin` doesn't handle Hybrid Attributes.
My propositions to handle this:
 * just override the method and add serialization of needed attributes manually
 * you can just add this feature :) I would really appreciate it because currently my time is quite limited
   I see it as adding `hybrid_attributes` param here http://prntscr.com/nrfwv4 and serialize them in similar way as it's currently implemented for relations

Thank you for your notes and request.
I really appreciate it!

**Comment by omrihar** [comment]
Hi @absent1706 !
Thanks for your response! I still didn't need to use the SerializeMixin so I didn't make any progress on this just yet... Thanks for the pointers and if I will get to work on this I'll also try to provide a PR.

Cheers,
Omri

**Comment by absent1706** [comment]
Thanks, @omrihar, looking forward for your PR!)
