### ISSUE TITLE
Question: was v1.1 deleted from pypi?

### ISSUE THREAD

**Issue by gyermolenko** [absent1706/sqlalchemy-mixins#37]

**Comment by absent1706** [comment]
Hi!
Yes, it was deleted because 1.2 code unintentionally deployed to PyPi as v1.1.
This was made to prevent end-user confusion. 

Also note that 1.2 was deleted  from PyPi too because it had big compatibility issue (fixed in 1.2.1).

PyPi now looks like this
![PyPi actual state screenshot](https://user-images.githubusercontent.com/1609763/78048887-0a5d0600-7383-11ea-839e-80d975a1a013.jpg)

Sorry for any inconvenience

**Comment by gyermolenko** [comment]
thanks for the explanation!
