### ISSUE TITLE
How can I use count function at smart query? 

### ISSUE THREAD

**Issue by DYFeng** [absent1706/sqlalchemy-mixins#5]
I want to get the posts which has less than 10 comments.
something like
`Post.where(comments___count__lt=10).all()`

**Comment by absent1706** [comment]
Unfortunately, `SmartQueryMixin.smart_query` is not intended to work with aggregation functions like `COUNT`, `SUM` etc. And, for now, I don't see a way how to implement such feature. But thanks for idea!

====

Generally speaking, filtering by aggregated function is quite complex task in SQL.
For your task, SQL should look like 
```sql
SELECT * FROM post 
LEFT JOIN comment ON post.id = comment.post_id 
GROUP BY post.id 
HAVING count(comment.id) < 10
```

Corresponding SQLAlchemy code will be
```python
Post.query.outerjoin(Post.comments).group_by(Post.id).having(func.count(Comment.id) < 10).all()
```
You can test above code on [examples/all_features.py](https://github.com/absent1706/sqlalchemy-mixins/blob/master/examples/all_features.py#L67)

====

In real project, I prefer to have a computed `comments_count` field in `post` table. This field is updated automatically due to [this awesome plugin](https://sqlalchemy-utils.readthedocs.io/en/latest/aggregates.html#simple-aggregates). It simplifies query building and reduces database load.

So I have 
```python
class Post
   # ...
   @aggregated('comments', sa.Column(sa.Integer))
   def comment_count(self):
      return sa.func.count('1')
```

And just write
```python
Post.where(comments_count__lt=10).all()
```

I strongly recommend you such approach

**Comment by DYFeng** [comment]
In Django,it's easy be done with annotate

```
from django.db.models import Count
User.objects.annotate(page_count=Count('page')).filter(page_count__gte=2).count()
```

**Comment by absent1706** [comment]
Thank you for information, I will think on it!
